config/routes.rb
Rails.application.routes.draw do

  resource :cart, only: [:show]
  resources :line_items, only: [:create, :update, :destroy]
  resources :charges

  root to: 'books#index'

  get 'books' => 'books#index', as: 'home'
  get 'show/:id' => 'books#show', as: 'book_show'
  get 'search' => 'books#search', as: 'book_search'
  get 'category' => 'books#category', as: 'book_category'

  get 'customers/show/:id' => 'customers#show', as: 'show_customer'
  get 'customers/new' => 'customers#new', as: 'new_customer'
  post 'customers' => 'customers#create'

  get 'about' => 'books#about', as: 'about'
  get 'contact' => 'books#contact', as: 'contact'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'line_items/create'
  get 'line_items/update'
  get 'line_items/destroy'
  get 'carts/show'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, :description, :stock_quantity, :price, presence: true
  validates :name, uniqueness: true, length: {minimum: 7}

  has_many :line_items
  belongs_to :category
  has_many :orders, :through => :line_items



  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :description, presence: true

  has_many :books
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, :address, :city, :postal_code, :email, :password, presence: true
  validates :email, :password, uniqueness: true
  # validates_confirmation_of :password
  has_many :orders


end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :order

  validates :quantity, :price, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  validate :book_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      book.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def book_present
    if book.nil?
      errors.add(:book, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:price] = quantity * self[:unit_price]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  validates :pst_rate, :gst_rate, presence: true

  has_many :line_items
  has_many :books, :through => :line_items
  belongs_to :customer

  #Sopping cart
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    line_items.collect { |li| li.valid? ? (li.quantity * li.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.status = OrderStatus.find(1).name
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_categories, :load_line_item

  def index
    @books = Book.page(params[:page]).per(3)
  end

  def search
    @books = Book.all
    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC").page(params[:page]).per(3)
    else
      @books = Book.all.order('created_at ASC').page(params[:page]).per(3)
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def category
    @category = Category.find(params[:id])
    @books = Book.where("category_id = ?", @category.id).page(params[:page]).per(3)
  end

  def about
    @about = About.all.first
  end

  def contact
    @contact = Contact.all.first
  end

  private
  def load_categories
    @categories = Category.all
  end

  def load_line_item
    @line_item = current_order.line_items.new
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = session[:amount].to_i

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'cad'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customer = Customer.order(:full_name)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to show_customer_path(@customer)
    else
      render :new
    end
  end
  
  private

  def customer_params
    params.require(:customer).permit(:full_name,:address,:city,:postal_code,:email,:phone_number,:password,:notes)
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    @order = current_order
    @line_item = @order.line_items.new(line_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @line_item = @order.line_items.find(params[:id])
    @line_item.update_attributes(line_item_params)
    @line_items = @order.line_items
    redirect_to cart_path
  end

  def destroy
    @order = current_order
    @line_item = @order.line_items.find(params[:id])
    @line_item.destroy
    @line_items = @order.line_items
    redirect_to cart_path
  end

  private
    def line_item_params
      params.require(:line_item).permit(:quantity, :book_id, :order_id, :price)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @customer = Customer.find_by(email: params[:session][:email])
    if @customer && @customer.password == params[:session][:password]
      log_in(@customer)
      redirect_to root_url
    else
      flash[:notice] = "The username is not found or password is incorrect."
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(customer)
    session[:customer_id] = customer.id
    session[:customer_name] = customer.full_name
  end

  def log_out
    reset_session
  end
end

app/views/books/_book.html.erb
<div class="card">
  <div class="card-block">
    <%= image_tag book.image, class: "rounded mx-auto d-block", size: "200x300" %>
    <h4 class="card-title"><%= book.name %></h4>
    <p class="card-text">Price: <strong>$<%= book.price %></strong></p>
    <%= link_to 'Show', book_show_path(book), class: "btn btn-primary" %>
  </div>
</div>

app/views/books/_header.html.erb
<p></p>
<h4>Welcome to Your Bookstore!<h4>
<nav class="nav text-xs-right">
  <% if session[:customer_name].nil?%>
    <%= link_to "Sign Up", new_customer_path, class: "nav-link" %>
    <%= link_to "Login", login_path, class: "nav-link" %>
  <%else%>
    <%= link_to "#{session[:customer_name]}", '#', class: "nav-link" %>
    <%= link_to "Log out", logout_path, class: "nav-link" %>
  <%end%>
</nav>

<h1>Mr. Levinson's Bookstore</h1>

  <div class="card card-block text-xs-right">
    <div class="row">
      <div class="col-sm-4">
      </div>
       <div class="col-sm-4">
        <h5>Your favorite books at one place :-)</h5>
      </div>
      <div class="col-sm-4">
        <%= render 'layouts/cart_text' %>
      </div>
    </div>
  </div>

<div class="nav">
  <%= render partial: 'navbar' %>
</div>

app/views/books/_index.html.erb
<div class="card">
  <div class="card-block">
    <%= image_tag book.image, class: "card-img-top", size: "200x300" %>
    <h4 class="card-title"><%= book.name %></h4>
    <p class="card-text">Price: <strong>$<%= book.price %></strong></p>
    <%= link_to 'Show', book_show_path(book), class: "btn btn-primary" %>
  </div>
</div>

app/views/books/_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <%= link_to 'Home', home_path, class: "btn btn-primary", class: "nav-link" %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Category</a>
      <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
        <% @categories.each do |cat| %>
          <%= link_to "#{cat.name}", book_category_path(:id => cat.id), class: "dropdown-item" %>
        <%end%>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Orders</a>
    </li>
    <li class="nav-item">
      <%= link_to "Contacts", contact_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "About", about_path, class: "nav-link" %>
    </li>
  </ul>
  <!-- <form class="form-inline float-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form> -->
  <%= form_tag(book_search_path, :method => "get", id: "search-form", class: "form-inline float-xs-right") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Books", class: "form-control" %>
  <%= submit_tag "Search", class: "btn btn-outline-success" %>
  <% end %>
</nav>

app/views/books/_single.html.erb
<div class="card">
  <div class="card-block">
    <%= image_tag @book.image, class: "card-img-top", size: "200x300" %>
    <h4 class="card-title"><%= @book.name %></h4>
    <p class="card-text">Price: <strong>$<%= @book.price %></strong></p>
    <p class="card-text">Category: <strong><%= @book.category.name %></strong></p>
    <p class="card-text"><%= @book.description %></p>
    <%= link_to 'Back', home_path, class: "btn btn-primary" %>


    <div class="col-xs-4">
      <%= form_for @line_item, remote: true do |f| %>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :book_id, value: @book.id %>
            <%= f.hidden_field :order_id, value: session[:order_id] %>
            <%= f.hidden_field :price, value: @book.price %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/books/about.html.erb
<%= render partial: 'header' %>
<div class="card">
  <div class="card-block">
    <div>
      <h4>History</h4>
      <p><%= @about.history %></p>
    </div>
    <div>
      <h4>Mission</h4>
      <p><%= @about.mission %></p>
    </div>
  </div>
</div>

app/views/books/category.html.erb
<%= render partial: 'header' %>


<div class="card-deck-wrapper">
  <div class="card-deck">
      <%= render partial: 'book', collection: @books %>
  </div>
    <%= paginate @books %>
</div>

app/views/books/contact.html.erb
<%= render partial: 'header' %>

<div class="card">
  <div class="card-block">
    <div>
      <h4>You are welcome to contact us:</h4>
      <p>Phone: <strong><%= @contact.phone_number %></strong></p>
      <p>Email: <strong><%= @contact.email %></strong></p>
      <p>Location: <strong><%= @contact.address %></strong></p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render partial: 'header' %>

<% if @books.present? %>
<div class="card-deck-wrapper">
  <div class="card-deck">
      <%= render partial: 'book', collection: @books %>
  </div>
    <%= paginate @books %>
</div>
<% else %>
  <p>There are matches found for <strong><%= params[:search] %></strong>.</p>
<% end %>

<!-- <div class="card-deck-wrapper">
  <div class="card-deck">
      <%= render partial: 'book', collection: @books %>
  </div>
    <%= paginate @books %>
</div> -->



<!-- <%= form_tag(home_path, :method => "get", id: "search-form", class: "form-inline float-xs-right") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Books", class: "form-control" %>
<%= submit_tag "Search", class: "btn btn-outline-success" %>
<% end %> -->

app/views/books/search.html.erb
<%= render partial: 'header' %>

<% if @books.present? %>
<div class="card-deck-wrapper">
  <div class="card-deck">
      <%= render partial: 'book', collection: @books %>
  </div>
    <%= paginate @books %>
</div>
<% else %>
  <p>There are matches found for <strong><%= params[:search] %></strong>.</p>
<% end %>

app/views/books/show.html.erb
<%= render partial: 'header' %>

<%= render partial: 'single', object: @book %>

app/views/customers/index.html.erb
<h1>Customers#index</h1>
<p>Find me in app/views/customers/index.html.erb</p>

app/views/customers/new.html.erb
<h2>Create Your New Account</h2>
<div class="card">
  <div class="card-block">
    <%= form_for(@customer) do |f| %>
      <div class="form-group">
        <%= f.label :full_name %>
        <%= f.text_field :full_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :postal_code %>
        <%= f.text_field :postal_code, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <!-- <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %> -->
      <div class="form-group">
        <%= f.label :notes %>
        <%= f.text_area :notes, class: "form-control" %>
      </div>
      <%= submit_tag "Create Account", :class => "btn btn-primary" %>
    <%end%>
  </div>
</div>
<div><%= link_to 'Back', home_path, class: "btn btn-primary" %></div>

app/views/customers/show.html.erb
<h3>Customer Account Created Succesfully.</h3>
<p>Thank you for registration, <%= @customer.full_name%>!</p>
<p><%= link_to 'Back', home_path, class: "btn btn-primary" %></p>

app/views/line_items/create.html.erb
<h1>LineItems#create</h1>
<p>Find me in app/views/line_items/create.html.erb</p>

app/views/line_items/create.js.erb
<% if @order.errors.any? || @line_item.errors.any? %>
alert("Not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/line_items/destroy.html.erb
<h1>LineItems#destroy</h1>
<p>Find me in app/views/line_items/destroy.html.erb</p>

app/views/line_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/line_items/update.html.erb
<h1>LineItems#update</h1>
<p>Find me in app/views/line_items/update.html.erb</p>

app/views/line_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")