config/routes.rb
Rails.application.routes.draw do

  resource :cart, only: [:show]
  resources :line_items, only: [:create, :update, :destroy]
  resources :charges

  root to: 'books#index'

  get 'books' => 'books#index', as: 'home'
  get 'show/:id' => 'books#show', as: 'book_show'
  get 'search' => 'books#search', as: 'book_search'
  get 'category' => 'books#category', as: 'book_category'

  get 'customers/show/:id' => 'customers#show', as: 'show_customer'
  get 'customers/new' => 'customers#new', as: 'new_customer'
  post 'customers' => 'customers#create'

  get 'about' => 'books#about', as: 'about'
  get 'contact' => 'books#contact', as: 'contact'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'line_items/create'
  get 'line_items/update'
  get 'line_items/destroy'
  get 'carts/show'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, :description, :stock_quantity, :price, presence: true
  validates :name, uniqueness: true, length: {minimum: 7}

  has_many :line_items
  belongs_to :category
  has_many :orders, :through => :line_items



  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :description, presence: true

  has_many :books
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, :address, :city, :postal_code, :email, :password, presence: true
  validates :email, :password, uniqueness: true
  # validates_confirmation_of :password
  has_many :orders


end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :order

  validates :quantity, :price, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  validate :book_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      book.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def book_present
    if book.nil?
      errors.add(:book, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:price] = quantity * self[:unit_price]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  validates :pst_rate, :gst_rate, presence: true

  has_many :line_items
  has_many :books, :through => :line_items
  belongs_to :customer

  #Sopping cart
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    line_items.collect { |li| li.valid? ? (li.quantity * li.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.status = OrderStatus.find(1).name
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_categories, :load_line_item

  def index
    @books = Book.page(params[:page]).per(3)
  end

  def search
    @books = Book.all
    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC").page(params[:page]).per(3)
    else
      @books = Book.all.order('created_at ASC').page(params[:page]).per(3)
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def category
    @category = Category.find(params[:id])
    @books = Book.where("category_id = ?", @category.id).page(params[:page]).per(3)
  end

  def about
    @about = About.all.first
  end

  def contact
    @contact = Contact.all.first
  end

  private
  def load_categories
    @categories = Category.all
  end

  def load_line_item
    @line_item = current_order.line_items.new
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = session[:amount].to_i

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'cad'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customer = Customer.order(:full_name)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to show_customer_path(@customer)
    else
      render :new
    end
  end
  
  private

  def customer_params
    params.require(:customer).permit(:full_name,:address,:city,:postal_code,:email,:phone_number,:password,:notes)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @customer = Customer.find_by(email: params[:session][:email])
    if @customer && @customer.password == params[:session][:password]
      log_in(@customer)
      redirect_to root_url
    else
      flash[:notice] = "The username is not found or password is incorrect."
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(customer)
    session[:customer_id] = customer.id
    session[:customer_name] = customer.full_name
  end

  def log_out
    reset_session
  end
end

app/views/carts/_cart_row.html.erb
<div class="card">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= book.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for line_item, remote: true do |f| %>
        <h4 class="text-right">Price: <span style="color: green"><%= number_to_currency line_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: line_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :book_id, value: book.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update", class: "btn btn-primary" %>
              <%= link_to "Delete", line_item, { data: { confirm: "Are you sure you wish to delete the book '#{line_item.book.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-warning" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency line_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>

</div>

app/views/carts/_shopping_cart.html.erb
<% if !@line_item.nil? && @line_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @line_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @line_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "Back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @line_items.each do |line_item| %>
    <%= render 'carts/cart_row', book: line_item.book, line_item: line_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<p></p>
  <%= render "shopping_cart" %>
  <div class="row text-xs-right">
    <%= render "charges/new" %>
  </div>
<%= link_to 'Back', home_path, class: "btn btn-primary" %>

app/views/charges/_new.html.erb
<% session[:amount] = current_order.subtotal * 100 %>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <h4 class="text-right">Total Amount: <%= number_to_currency current_order.subtotal %></h4>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount=<%= session[:amount] %>
          data-locale="auto"
          data-currency="cad"
          data-billingAddress="true"
          data-shippingAddress="true">
  </script>
<% end %>

app/views/charges/create.html.erb
<p>
</p>
<div class="card">
  <h2>Thank you, the amount paid: <strong><%= number_to_currency current_order.subtotal %></strong>!</h2>
</div>
<p>
  <%= link_to 'Back', home_path, class: "btn btn-primary" %>
</p>

app/views/charges/new.html.erb
<%= render "new" %>